// Guards the one file the browser animates: public/data/arad-bucharest-search.json.
//
// Two independent things can go wrong with it, and this script checks both.
//
//   Freshness. The JSON is generated by `wasm/src/bin/export_sample.rs` and then
//   committed. Nothing regenerates it on demand, so an engine change leaves it
//   stale: parity and golden go red for the engine, someone updates the goldens,
//   CI goes green again -- and the browser is still animating the old numbers.
//   Checking the shape of the file cannot see this, because a stale file is a
//   perfectly well-shaped file. So this re-runs the exporter and diffs.
//
//   The road table. lib/romaniaGraph.ts holds its own copy of all 23 roads, used
//   to draw the map and its distance labels. It is a fourth encoding of the table
//   that I2 pins across Rust, C++ and Python, and it sits outside that invariant.
//   If it drifts, the map shows one distance while the search uses another.
//
// The contract assertions below are a separate concern from both: they pin the
// field names components/sample/SampleGraphDemo.tsx reads, so a rename in
// wasm/src/metrics.rs fails here rather than as `undefined` in the browser.

import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const repo = fileURLToPath(new URL("..", import.meta.url));
const read = (relative) => readFileSync(new URL(relative, import.meta.url), "utf8");

const SAMPLE_PATH = "public/data/arad-bucharest-search.json";
const REGENERATE =
  "  cargo run --quiet --manifest-path wasm/Cargo.toml --bin export_sample \\\n" +
  `    > ${SAMPLE_PATH}`;

// ------------------------------------------------------------------- freshness
const sample = JSON.parse(read(`../${SAMPLE_PATH}`));

const engine = JSON.parse(
  execFileSync(
    "cargo",
    ["run", "--quiet", "--manifest-path", "wasm/Cargo.toml", "--bin", "export_sample"],
    { cwd: repo, encoding: "utf8", maxBuffer: 64 * 1024 * 1024, stdio: ["ignore", "pipe", "inherit"] },
  ),
);

assert.deepEqual(
  sample,
  engine,
  `${SAMPLE_PATH} no longer matches what the engine produces.\n` +
    `If the engine change was intended, regenerate the sample:\n${REGENERATE}`,
);

// ------------------------------------------------------------------ road table
// Both tables are read as text rather than imported: graph.rs is Rust, and
// romaniaGraph.ts carries presentation coordinates this script has no opinion on.
function roadsFrom(source, marker, pattern, label) {
  const start = source.indexOf(marker);
  assert.notEqual(start, -1, `${label}: could not find "${marker}" -- update this script`);
  const edges = [...source.slice(start).matchAll(pattern)].map((match) => {
    const [a, b, distance] = match.slice(1).map(Number);
    // Roads are undirected; order the endpoints so the two files compare equal
    // even if one of them ever lists a road the other way round.
    return [Math.min(a, b), Math.max(a, b), distance].join("-");
  });
  assert.equal(edges.length, 23, `${label}: expected 23 roads, found ${edges.length}`);
  return edges.sort();
}

assert.deepEqual(
  roadsFrom(read("../lib/romaniaGraph.ts"), "roads: [", /\[\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*\]/g, "lib/romaniaGraph.ts"),
  roadsFrom(read("../wasm/src/graph.rs"), "let roads:", /\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*\)/g, "wasm/src/graph.rs"),
  "lib/romaniaGraph.ts and wasm/src/graph.rs disagree about the roads.\n" +
    "The map would draw distances the search does not use. Make them match.",
);

// -------------------------------------------------------------------- contract
const resultKeys = [
  "cost",
  "expanded",
  "explored_order",
  "generated",
  "path",
  "peak_frontier",
  "peak_payload_bytes",
  "peak_records",
  "trace",
].sort();

assert.deepEqual(Object.keys(sample).sort(), ["astar", "ucs"], "sample must contain only UCS and A*");

for (const algorithm of ["ucs", "astar"]) {
  const result = sample[algorithm];
  assert.deepEqual(Object.keys(result).sort(), resultKeys, `${algorithm} result contract changed`);
  assert.equal(result.path[0], 0, `${algorithm} path must start at Arad`);
  assert.equal(result.path.at(-1), 12, `${algorithm} path must end at Bucharest`);
  assert.equal(result.trace.length, result.expanded, `${algorithm} needs one trace frame per expansion`);
  assert.equal(result.explored_order.length, result.expanded, `${algorithm} explored count must match expanded`);

  result.trace.forEach((frame, index) => {
    assert.deepEqual(
      Object.keys(frame).sort(),
      ["discovered", "expanded_city", "expanded_cost", "frontier"],
      `${algorithm} frame ${index} contract changed`,
    );
    assert.equal(frame.expanded_city, result.explored_order[index], `${algorithm} frame ${index} has the wrong city`);
    assert.ok(Number.isFinite(frame.expanded_cost), `${algorithm} frame ${index} has an invalid cost`);
    assert.ok(Array.isArray(frame.frontier), `${algorithm} frame ${index} frontier must be an array`);
    assert.ok(Array.isArray(frame.discovered), `${algorithm} frame ${index} discovered must be an array`);

    for (const node of frame.frontier) {
      assert.ok(Number.isInteger(node.city) && node.city >= 0 && node.city < 20, "frontier city must be valid");
      assert.ok(Number.isFinite(node.cost) && Number.isFinite(node.priority), "frontier costs must be finite");
    }
    for (const node of frame.discovered) {
      assert.ok(Number.isInteger(node.city) && node.city >= 0 && node.city < 20, "discovered city must be valid");
      assert.ok(Number.isFinite(node.cost), "discovered cost must be finite");
      assert.ok(node.parent === null || Number.isInteger(node.parent), "discovered parent must be a city or null");
    }
  });

  assert.equal(result.trace.at(-1).expanded_city, 12, `${algorithm} final frame must expand Bucharest`);
}

assert.equal(sample.ucs.cost, sample.astar.cost, "UCS and A* costs must match");
console.log("frontend sample contract: PASS");
